# Generated by Django 5.1.1 on 2024-10-12 18:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finaldraft', '0002_remove_groupinfo_is_admin_remove_groupinfo_member_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupinfo',
            name='member',
            field=models.ManyToManyField(related_name='groupinfo', to=settings.AUTH_USER_MODEL),
        ),
    ]
