# Generated by Django 5.1.1 on 2024-10-13 14:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finaldraft', '0003_alter_groupinfo_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='reviewee',
            field=models.ManyToManyField(blank=True, related_name='reviewee_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='reviewer',
            field=models.ManyToManyField(blank=True, related_name='reviewer_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
