# Generated by Django 5.1.1 on 2024-10-13 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finaldraft', '0004_alter_assignment_reviewee_alter_assignment_reviewer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='iteration_no',
        ),
        migrations.AlterField(
            model_name='groupinfo',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='groupinfo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='approved_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='remark',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='submission',
            name='reviewee',
            field=models.ManyToManyField(blank=True, related_name='reviewee_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='reviewer',
            field=models.ManyToManyField(blank=True, related_name='reviewer_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='assignment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='finaldraft.assignment'),
        ),
    ]
