# Generated by Django 5.1.1 on 2024-10-15 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finaldraft', '0005_remove_submission_iteration_no_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='subtask',
            field=models.ManyToManyField(blank=True, related_name='submissions', to='finaldraft.subtask'),
        ),
        migrations.CreateModel(
            name='SubtaskSubmissionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('reviewee', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='finaldraft.submission')),
                ('subtask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finaldraft.subtask')),
            ],
        ),
    ]
