# Generated by Django 5.1.1 on 2024-10-17 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finaldraft', '0008_alter_submission_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
