# Generated by Django 5.1.1 on 2024-10-17 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finaldraft', '0009_alter_submission_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubtaskInfo',
        ),
    ]
