# Generated by Django 5.1.1 on 2024-10-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finaldraft', '0014_attachment_file_attachment_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='type',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='finaldraft/data/files/'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='finaldraft/data/images/'),
        ),
    ]
