# Generated by Django 5.1.1 on 2024-10-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finaldraft', '0015_remove_attachment_type_alter_attachment_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='url',
        ),
        migrations.AddField(
            model_name='submission',
            name='repo_link',
            field=models.URLField(blank=True),
        ),
    ]
