# Generated by Django 5.1.1 on 2024-10-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finaldraft', '0017_attachment_is_for_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='is_for_submission',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='finaldraft/media/files/'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='finaldraft/media/images/'),
        ),
    ]
