# Generated by Django 5.1.1 on 2024-10-21 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finaldraft', '0018_remove_attachment_is_for_submission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finaldraft.assignment'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finaldraft.submission'),
        ),
    ]
