# Generated by Django 5.1.1 on 2024-09-28 03:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.date.today)),
                ('deadline', models.DateField()),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(max_length=200)),
                ('date', models.DateField(default=datetime.date.today)),
                ('is_completed', models.BooleanField()),
                ('iteration_no', models.IntegerField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finaldraft.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('URL', 'URL'), ('PDF', 'PDF'), ('IMAGE', 'Image')], max_length=50)),
                ('url', models.URLField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finaldraft.assignment')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finaldraft.submission')),
            ],
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(default=datetime.date.today)),
                ('deadline', models.DateField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finaldraft.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='SubtaskInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iteration_no', models.IntegerField()),
                ('is_completed', models.BooleanField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finaldraft.submission')),
                ('subtask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finaldraft.subtask')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_no', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finaldraft.role')),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='approved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_submissions', to='finaldraft.user'),
        ),
        migrations.AddField(
            model_name='submission',
            name='reviewee',
            field=models.ManyToManyField(related_name='reviewee_submissions', to='finaldraft.user'),
        ),
        migrations.AddField(
            model_name='submission',
            name='reviewer',
            field=models.ManyToManyField(related_name='reviewer_submissions', to='finaldraft.user'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finaldraft.user'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='reviewee',
            field=models.ManyToManyField(related_name='reviewee_assignments', to='finaldraft.user'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='reviewer',
            field=models.ManyToManyField(related_name='reviewer_assignments', to='finaldraft.user'),
        ),
    ]
